package appVO;

public class voCons {

	public static final int Type_0 = 1;
	public static final int Flow_Type_0 = 2;
	public static final int Grampanchayat_0 = 3;
	public static final int VO_Name_1 = 4;
	public static final int VO_Name_in_Local_2 = 5;
	public static final int Formation_Date_3 = 6;
	public static final int Promoted_by_4 = 7;
	public static final int New_Revived_Co_opted_104 = 8;
	public static final int Promoters_name_204 = 9;
	public static final int Revival_Date_304 = 10;
	public static final int Co_option_Date_404 = 11;
	public static final int Meeting_Frequency_5 = 12;
	public static final int Date_105 = 13;
	public static final int Date_205 = 14;
	public static final int Monthly_day_305 = 15;
	public static final int Day_405 = 16;
	public static final int Financial_Intermediation_6 = 17;
	public static final int Compulsory_Saving_Frequency_106 = 18;
	public static final int Compulsory_Saving_Amount_206 = 19;
	public static final int Compulsory_Saving_Interest_Rate_Annual_306 = 20;
	public static final int Voluntary_Saving_406 = 21;
	public static final int Bookkeeper_Identified__7 = 22;
	public static final int Bookkeeper_Identified__107 = 23;
	public static final int Bookkeepers_Name_207 = 24;
	public static final int Bookkeeper_s_Mobile_No_307 = 25;
	public static final int Tenure_of_elected_Office_Bearers_8 = 26;
	public static final int VO_resolution_copy_9 = 27;
	public static final int Status_10 = 28;
	public static final int Expected_Error_Message_99999 = 29;
	public static final int Gram_Panchayat_11 = 30;
	public static final int Village__Town_111 = 31;
	public static final int CBO_Name_12 = 32;
	public static final int EC_Member_Name_112 = 33;
	public static final int Designation_in_VO_212 = 34;
	public static final int From_Date_412 = 35;
	public static final int Signatory_512 = 36;
	public static final int From_Date_612 = 37;
	public static final int Mobile_belongs_to_13 = 38;
	public static final int Mobile_number_113 = 39;
	public static final int Name_in_Bank_Passbook_15 = 40;
	public static final int IFSC_Code_115 = 41;
	public static final int Bank_name_215 = 42;
	public static final int Bank_Branch_315 = 43;
	public static final int Account_number_415 = 44;
	public static final int Re_Type_Account_No_515 = 45;
	public static final int Account_opening_date_615 = 46;
	public static final int Passbook_First_Page_715 = 47;
	public static final int Is_Default_815 = 48;
}
